#!/bin/bash
###########################################################################
#
# Copyright (c) 2017 Intel Deutschland GmbH, All Rights Reserved.
#
#
# Contact: harts_support@intel.com
#
###########################################################################

curl -X DELETE http://localhost:9999/api/v1/stack

